FORMAT: 1A
HOST: https://salty-temple-18987.herokuapp.com/

# Questions API

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/api/questions/create-question]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "My name is",
                "hint": "Seriously?"
            }
        ]

### Create a New Question [POST]

Creating a new question

+ Request (application/json)

         {
                "id" : 1
                "question": "Hola,my name is",
                "hint": "Come estas?"
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/1

    + Body

            {
                 "question": "Hola,my name is",
                "hint": "Come estas?"
            }
            
## Get question by ID [/api/answers/get-question-by-id]

### Get question by ID [POST]

+ Request (application/json)

         {
                "id": "1",
        }
        
+ Response 201 (application/json)

    + Headers

            Location: /questions/1

    + Body

            {
                "id": "1",
                "question": "Hola,my name is",
                "hint": "Come estas?"
            }         
        
## Update question [/api/questions/update-question]

### Update Question [POST]

+ Request (application/json)

         {
                "id": "1",
        }
        
+ Response 201 (application/json)

    + Headers

            Location: /questions/1

    + Body

            {
                "id": "1",
                "question": "Hi,my name is",
                "hint": "How are you?"
            }